export enum DatabaseCollection {
  PROPOSALS = "proposals",
  INVOICES = "invoices",
  TEMPLATES = "templates",
  ORGANIZATIONS = "organizations",
  USERS = "users",
  WORKFLOWS = "workflows",
  BRAND_SITES = "brandSites",
  CONTACTS = "contacts",
  LEADS = "leads",
  PRODUCTS = "products",
  EMAIL_TEMPLATE_MAPPINGS = "emailTemplateMappings",
  EXTRACTION_JOBS = "extractionJobs",
  TEMPLATE_PATTERNS = "templatePatterns",
}
