export enum DatabaseCollection {
  PROPOSALS = "proposals",
  INVOICES = "invoices",
  TEMPLATES = "templates",
  ORGANIZATIONS = "organizations",
  USERS = "users",
  WORKFLOWS = "workflows",
  BRAND_SITES = "brandSites",
  CONTACTS = "contacts",
  LEADS = "leads",
  PRODUCTS = "products",
  EMAIL_TEMPLATE_MAPPINGS = "emailTemplateMappings",
  EMAIL_TEMPLATES = "emailTemplates",
  EXTRACTION_JOBS = "extractionJobs",
  TEMPLATE_PATTERNS = "templatePatterns",
  DUPLICATION_JOBS = "duplicationJobs",
  EXTERNAL_SOURCE_CONFIGS = "externalSourceConfigs",
  EXTERNAL_SOURCE_CACHE = "externalSourceCache",
  MARKETPLACE_TEMPLATES = "marketplaceTemplates",
  MARKETPLACE_REVIEWS = "marketplaceReviews",
}
