import { test } from "node:test";
import assert from "node:assert";
import {
  emailGenerationSchema,
  invoiceGenerationSchema,
  toCanonicalEmailTemplateData,
  toCanonicalInvoiceTemplateData,
  toMarketplaceTemplateData,
  toMarketplaceTemplateVersionData,
} from "./schemas";

const baseBrand = {
  fonts: ["Inter"],
  colors: {
    primary: "#111827",
    secondary: "#6b7280",
    accent: "#2563eb",
  },
  margins: { top: 40, right: 40, bottom: 40, left: 40 },
};

test("invoice generation schema and canonical conversion", () => {
  const stageA = invoiceGenerationSchema.parse({
    name: "Official EU Invoice",
    pageSize: "A4",
    brand: baseBrand,
    elements: [
      {
        id: "invoice-number",
        type: "input",
        x: 40,
        y: 40,
        width: 220,
        height: 24,
        binding: "invoiceNumber",
      },
    ],
    compliance: {
      region: "EU",
      requiredFields: [],
      autoFooter: true,
      complianceValidated: false,
    },
    productTableConfig: {
      itemsBinding: "items",
      columnMappings: [
        {
          columnBinding: "description",
          productField: "description",
          transform: "none",
          lockOnProductSelect: true,
        },
        {
          columnBinding: "unitPrice",
          productField: "price",
          transform: "currency_convert",
          targetCurrency: "EUR",
          lockOnProductSelect: true,
        },
      ],
      autoQuantity: false,
      defaultQuantity: 1,
      autoConvertCurrency: true,
      defaultCurrency: "EUR",
    },
  });

  const canonical = toCanonicalInvoiceTemplateData(stageA, "official-org");
  assert.strictEqual(canonical.orgId, "official-org");
  assert.strictEqual(canonical.status, "draft");
});

test("invoice generation schema fails for missing required fields", () => {
  const parsed = invoiceGenerationSchema.safeParse({
    description: "missing required fields",
  });
  assert.strictEqual(parsed.success, false);
});

test("email generation schema and canonical conversion", () => {
  const stageA = emailGenerationSchema.parse({
    name: "Invoice Sent",
    subject: "Your invoice {{invoice.number}}",
    htmlContent: "<p>Hello {{contact.name}}</p>",
    blocks: [],
    designTokens: {},
    allowedContexts: ["invoice_send"],
    placeholders: [
      {
        key: "invoice.number",
        source: {
          type: "entity_field",
          entity: "invoice",
          path: "invoice.number",
        },
      },
      {
        key: "contact.name",
        source: {
          type: "entity_field",
          entity: "contact",
          path: "contact.name",
        },
      },
    ],
    sections: {
      header: [],
      body: [],
      footer: [],
    },
  });

  const canonical = toCanonicalEmailTemplateData(stageA, "official-org");
  assert.strictEqual(canonical.orgId, "official-org");
  assert.strictEqual(canonical.status, "draft");
  assert.strictEqual(canonical.version, 1);
  assert.strictEqual(canonical.isSystemDefault, false);
  assert.strictEqual(canonical.isLocked, false);
});

test("marketplace data and version data parse through canonical schemas", () => {
  const templateData = toMarketplaceTemplateData({
    title: "Official EU Invoice",
    shortDescription: "Professional invoice template",
    description: "Draft generated by Genkit",
    type: "invoice",
    authorId: "admin-1",
    authorName: "Financely Team",
    isOfficial: true,
    isFeatured: false,
    status: "draft",
    templateContent: {
      name: "Official EU Invoice",
      pageSize: "A4",
      brand: baseBrand,
      elements: [],
    },
    previewImages: [],
    tags: ["official", "invoice"],
    category: "Invoicing",
    language: "en",
    country: "EU",
    ratingAverage: 0,
    ratingCount: 0,
    downloadCount: 0,
    version: 1,
    aiEnrichmentStatus: "done",
    sourceTemplateId: "official-eu-invoice-service-professional-en",
    sourceTemplateType: "invoice",
  });

  const versionData = toMarketplaceTemplateVersionData({
    marketplaceTemplateId: "template-1",
    version: 1,
    type: "invoice",
    title: "Official EU Invoice",
    templateContent: templateData.templateContent,
    sourceTemplateId: "official-eu-invoice-service-professional-en",
    sourceTemplateType: "invoice",
    createdBy: "admin-1",
    publishedAt: new Date().toISOString(),
    changelog: "initial",
  });

  assert.strictEqual(templateData.isOfficial, true);
  assert.strictEqual(versionData.version, 1);
});
