import { z } from "zod";
import { baseEntitySchema } from "./base";

export const inviteDataSchema = z.object({
  code: z.string().min(1), // Unique code generated by backend
  organizationId: z.string().min(1),
  invitedBy: z.string().min(1), // User ID who created the invite
  email: z.string().email(), // Email of the person being invited
  role: z.enum(["admin", "member", "viewer"]).default("member"), // Role for the invite
  status: z.enum(["active", "sent", "used", "expired", "revoked"]).default("active"),
  expiresAt: z.string(), // ISO date string
  usedAt: z.string().optional(), // ISO date string when used
  usedBy: z.string().optional(), // User ID who used the invite
  revokedAt: z.string().optional(), // ISO date string when revoked
  revokedBy: z.string().optional(), // User ID who revoked the invite
});

export type InviteData = z.infer<typeof inviteDataSchema>;

export const inviteSchema = baseEntitySchema.merge(inviteDataSchema);
export type Invite = z.infer<typeof inviteSchema>;

/**
 * Helper type for creating invites.
 * Omits server-managed fields.
 */
export type CreateInviteInput = Pick<InviteData, "organizationId" | "invitedBy" | "email"> & {
  expiresAt?: string; // Optional, defaults to 7 days from now
  role?: "admin" | "member" | "viewer"; // Optional, defaults to "member"
};

/**
 * Helper function to check if an invite is active and not expired.
 * 
 * @param invite - The invite to check
 * @returns true if the invite is active and not expired
 */
export function isInviteActive(invite: Invite): boolean {
  const now = new Date();
  const expiresAt = new Date(invite.expiresAt);
  // An invite is active if it's in "active" or "sent" status and not expired
  return (invite.status === "active" || invite.status === "sent") && expiresAt > now;
}

/**
 * Helper function to check if an invite has been used.
 * 
 * @param invite - The invite to check
 * @returns true if the invite has been used
 */
export function isInviteUsed(invite: Invite): boolean {
  return invite.status === "used";
}

/**
 * Helper function to check if an invite is expired.
 * 
 * @param invite - The invite to check
 * @returns true if the invite is expired
 */
export function isInviteExpired(invite: Invite): boolean {
  const now = new Date();
  const expiresAt = new Date(invite.expiresAt);
  return expiresAt <= now;
}
