import { getDatabaseService } from "../services/database-service";
import { getOrganizationRepository } from "../repositories/organization-repository";
import { getBrandSiteRepository } from "../repositories/brand-site-repository";
import { GeminiService } from "../services/gemini-service";
import { CloudflareService } from "../services/cloudflare-service";
import { FirebaseHostingService } from "../services/firebase-hosting-service";
import { logger } from "firebase-functions";

interface GenerateSiteInput {
  organizationId: string;
  brandName?: string;
  tone?: string;
}

interface GenerateSiteConfig {
  geminiApiKey: string;
  cloudflareApiToken: string;
  cloudflareZoneId: string;
  cloudflareBaseDomain: string;
  firebaseProjectId: string;
}

export async function handleGenerateSite(
  input: GenerateSiteInput,
  config: GenerateSiteConfig,
): Promise<{ id: string; url: string; status: string }> {
  const startTime = Date.now();
  logger.info("Starting site generation", {
    organizationId: input.organizationId,
    timestamp: new Date().toISOString(),
  });

  const databaseService = getDatabaseService();
  const organizationRepository = getOrganizationRepository(databaseService);
  const brandSiteRepository = getBrandSiteRepository(databaseService);

  const orgStartTime = Date.now();
  const organization = await organizationRepository.get({ id: input.organizationId });
  if (!organization) {
    throw new Error("Organization not found");
  }
  logger.info("Organization retrieved", {
    duration: Date.now() - orgStartTime,
    organizationName: organization.name,
  });

  const brandName = input.brandName || organization.name;
  const tone = input.tone || "professional";
  const brandColors = organization.settings?.brandColors || {
    primary: "#2563eb",
    secondary: "#6b7280",
    accent: "#10b981",
  };
  const logoUrl = organization.settings?.branding?.customLogo || organization.logoUrl;

  // Find existing brand site (should already exist from init)
  const existingSites = await brandSiteRepository.getAll({
    queryConstraints: [
      { field: "organizationId", operator: "==", value: input.organizationId },
    ],
  });

  if (existingSites.length === 0) {
    throw new Error("Brand site not found. Please initiate generation first.");
  }

  const brandSite = existingSites[0];
  const brandSiteId = brandSite.id;

  // Verify status is pending (should be set by init function)
  if (brandSite.status !== "pending") {
    logger.warn("Brand site status is not pending, updating to pending", {
      brandSiteId,
      currentStatus: brandSite.status,
    });
    await brandSiteRepository.update({
      id: brandSiteId,
      data: {
        status: "pending",
      },
    });
  }

  try {
    await brandSiteRepository.update({
      id: brandSiteId,
      data: {
        status: "generating",
      },
    });

    const geminiStartTime = Date.now();
    const geminiService = new GeminiService({
      apiKey: config.geminiApiKey,
      model: "gemini-2.5-flash",
    });

    // Check if this is a section regeneration
    const sectionType = (brandSite.metadata as { regenerateSectionType?: "hero" | "about" | "features" | "contact" })?.regenerateSectionType;

    let html: string;

    if (sectionType && brandSite.html) {
      logger.info("Calling Gemini API for section regeneration", {
        brandName,
        sectionType,
        model: "gemini-2.5-flash",
      });

      html = await geminiService.regenerateSection(
        {
          brandName,
          colors: brandColors,
          logoUrl,
          tone,
        },
        sectionType,
        brandSite.html,
      );

      logger.info("Section regenerated by Gemini", {
        duration: Date.now() - geminiStartTime,
        sectionType,
        htmlLength: html.length,
      });
    } else {
      logger.info("Calling Gemini API for HTML generation", {
        brandName,
        model: "gemini-2.5-flash",
      });

      html = await geminiService.generateSiteHtml({
        brandName,
        colors: brandColors,
        logoUrl,
        tone,
      });

      logger.info("HTML generated by Gemini", {
        duration: Date.now() - geminiStartTime,
        htmlLength: html.length,
      });
    }

    await brandSiteRepository.update({
      id: brandSiteId,
      data: {
        html,
      metadata: {
        generatedAt: new Date().toISOString(),
        model: "gemini-2.5-flash",
        version: (brandSite?.metadata?.version || 0) + 1,
      },
        status: "deploying",
      },
    });

    const subdomain = generateSubdomain(brandName);
    let siteId = `brand-${brandSiteId}`;

    const hostingStartTime = Date.now();
    
    if (!config.firebaseProjectId || config.firebaseProjectId.trim() === "") {
      throw new Error("Firebase Project ID is required for hosting");
    }

    logger.info("Initializing Firebase Hosting Service", {
      projectId: config.firebaseProjectId,
    });

    const hostingService = new FirebaseHostingService({
      projectId: config.firebaseProjectId.trim(),
    });

    logger.info("Creating or getting Firebase Hosting site", { siteId });
    const createdSite = await hostingService.createSite(siteId);
    
    // Validate response has siteId
    if (!createdSite?.siteId) {
      throw new Error("Firebase Hosting API returned invalid response: missing siteId");
    }
    
    // Use the siteId from the response (works for both new and existing sites)
    siteId = createdSite.siteId;
    logger.info("Firebase Hosting site ready", {
      duration: Date.now() - hostingStartTime,
      siteId,
      originalSiteId: `brand-${brandSiteId}`,
      siteName: createdSite.name,
    });

    const deployStartTime = Date.now();
    
    // Validate siteId before deployment
    if (!siteId || typeof siteId !== 'string') {
      throw new Error("Invalid site ID: cannot deploy without a valid site ID");
    }
    
    logger.info("Deploying site to Firebase Hosting", { siteId, htmlLength: html.length });
    const deployedUrl = await hostingService.deploySite(
      siteId,
      [{ path: "index.html", contents: html }],
      `Deploy ${brandName} site`,
    );
    logger.info("Site deployed to Firebase Hosting", {
      duration: Date.now() - deployStartTime,
      deployedUrl,
    });

    // For regeneration, skip Cloudflare subdomain creation (use Firebase Hosting URL directly)
    // For new sites, create Cloudflare subdomain
    const isRegeneration = !!sectionType || !!brandSite.html;

    let finalUrl: string;

    if (isRegeneration) {
      // Regeneration: use Firebase Hosting URL directly
      finalUrl = deployedUrl;
      logger.info("Skipping Cloudflare subdomain for regeneration", {
        deployedUrl,
      });

      await brandSiteRepository.update({
        id: brandSiteId,
        data: {
          status: "success",
          deployedUrl: finalUrl,
          // Clear the regenerateSectionType from metadata
          metadata: {
            ...(brandSite.metadata || {}),
            version: brandSite.metadata?.version || 1,
            generatedAt: brandSite.metadata?.generatedAt,
            model: brandSite.metadata?.model,
            regenerateSectionType: undefined,
          },
        },
      });
    } else {
      // New site: create Cloudflare subdomain
      const cloudflareStartTime = Date.now();
      const cloudflareService = new CloudflareService({
        apiToken: config.cloudflareApiToken,
        zoneId: config.cloudflareZoneId,
        baseDomain: config.cloudflareBaseDomain,
      });

      logger.info("Creating Cloudflare subdomain", { subdomain });
      const deployedHost = new URL(deployedUrl).hostname;
      finalUrl = await cloudflareService.createSubdomain(
        subdomain,
        deployedHost,
      );
      logger.info("Cloudflare subdomain created", {
        duration: Date.now() - cloudflareStartTime,
        subdomainUrl: finalUrl,
      });

      await brandSiteRepository.update({
        id: brandSiteId,
        data: {
          status: "success",
          subdomain,
          deployedUrl: finalUrl,
        },
      });
    }

    const totalDuration = Date.now() - startTime;
    logger.info("Site generated and deployed successfully", {
      brandSiteId,
      subdomain: isRegeneration ? undefined : subdomain,
      url: finalUrl,
      isRegeneration,
      totalDuration,
      totalDurationSeconds: Math.round(totalDuration / 1000),
    });

    return {
      id: brandSiteId,
      url: finalUrl,
      status: "success",
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    logger.error("Failed to generate site", {
      brandSiteId,
      error: errorMessage,
    });

    await brandSiteRepository.update({
      id: brandSiteId,
      data: {
        status: "failed",
        error: errorMessage,
      },
    });

    throw new Error(`Failed to generate site: ${errorMessage}`);
  }
}

function generateSubdomain(brandName: string): string {
  if (!brandName || typeof brandName !== 'string') {
    throw new Error("Brand name is required to generate subdomain");
  }
  
  return brandName
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .substring(0, 50);
}

